export const MENU = '/'
export const DUAL = '/dual'
export const SETTINGS = '/settings'
export const HISTORY = '/history'
export const LEVEL = '/level'
export const SINGLE_EASY = '/single_easy'
export const SINGLE_MEDIUM = '/single_medium'
export const SINGLE_HARD = '/single_hard'